language: c

dist: jammy

os: linux

compiler:
  - gcc
  - clang

sudo: true

addons:
  apt:
    packages:
      - libxrandr-dev
      - libpango1.0-dev
      - checkinstall
      - clang
      - gcc

script:
  - ./configure --prefix=/usr
  - make
  - make test
  - sudo checkinstall --install=no -y

